version: "3.1"
services:

    debian:
      image: debian:latest
      container_name: pubs-debian
      working_dir: /application
      command: tail -f /dev/null 
      environment:
        - SERVICE_HOST_ARGS__PORT=3000
        - NREPL__PORT=7884
        - NREPL__BIND=0.0.0.0
        - MYSQL__HOST=pubs-mysql
        - MYSQL__USER=root
        - MYSQL__PASSWORD=PUk8zFrxsqsS83
        - MYSQL__DBNAME=example
        - FILES__ROOT=/srv/example/projects/
        - FILES__DIR=/files
        - DATACITE_DOI__USERPW=PURDUE.DDCC:Purduedatacite2018
        - SECRET=hd3SqnDQ0gNuGVxbfFH9AmsU1KeTv6site
        - DB__MAIN__URL=mysql://pubs-mysql:3306/example?user=root&password=PUk8zFrxsqsS83&zeroDateTimeBehavior=convertToNull
      volumes:
        - ./hzn-pubs-api:/application
        - ./data/srv:/srv
        - ./hzn-session-auth:/hzn-session-auth
      ports:
        - "3000:3000"
        - "7884:7884"
      networks:
        - hz-internal

## I'm gonna leave this here for notes, but not necessary - JBG
#    hubcap:
#      image: debian:latest
#      container_name: hub-hubcap
#      working_dir: /application
#      command: tail -f /dev/null 
#      environment:
#        - SERVICE_HOST_ARGS__PORT=3001
#        - NREPL__PORT=7885
#        - NREPL__BIND=0.0.0.0
#        - MONGODB__HOST=mongodb
#      volumes:
#        - ../hzn-hubcap-api:/application
#        - ../hub/data/srv:/srv
#      ports:
#        - "3001:3001"
#        - "7885:7885"
#      networks:
#        - hz-internal

    mysql:
      image: mysql:5.6
      container_name: pubs-mysql
      working_dir: /application
      networks:
        - hz-internal
      environment:
        - MYSQL_ROOT_PASSWORD=PUk8zFrxsqsS83
      ports:
        - "3306:3306"
      volumes:
        - .:/application
        - ./hzcms-docker/data/dump:/docker-entrypoint-initdb.d
        - ./data/mysql:/var/lib/mysql

    webserver:
      image: nginx:alpine
      container_name: pubs-webserver
      working_dir: /application
      networks:
        - hz-internal
      volumes:
        - ./hzcms-docker/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app-pubs.conf:/etc/nginx/config.d/app-pubs.conf
        - ./hzcms-docker/server.crt:/etc/ssl/server.crt
        - ./hzcms-docker/server.key:/etc/ssl/server.key
        - ./hubzero-cms:/application/public
        - ./hzcms-docker/app:/application/public/app
        - ./com_pubs:/application/public/app/components/com_pubs
        - ./hzn-pubs-spa/resources/public/js/compiled:/application/public/app/components/com_pubs/site/assets/js/compiled
      ports:
        - "80:80"
        - "443:443"

    php-fpm:
      build: hzcms-docker/docker/php-fpm
      container_name: pubs-php-fpm
      working_dir: /application
      networks:
        - hz-internal
      volumes:
        - ./hubzero-cms:/application/public
        - ./hzcms-docker/app:/application/public/app
        - ./com_pubs:/application/public/app/components/com_pubs
        - ./hzn-pubs-spa/resources/public/js/compiled:/application/public/app/components/com_pubs/site/assets/js/compiled
        - ./hzcms-docker/docker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
        - ./data/srv:/srv

## Is used by hubcap, commented out above - JBG
#    mongodb:
#      container_name: hub-mongodb
#      image: mongo:latest
#      volumes:
#        - ./data/mongodb:/data/mongodb
#        - ./data/configdb:/data/configdb
#      ports:
#        - "27017:27017"
#      networks:
#        - hz-internal

networks:
  hz-internal:
